[package]
name = "yug"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
colored = "2.0.0"
glob = "0.3.0"
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.5.10"
